/**
 * softProof — faithful CMYK soft-proof of a print, in the browser.
 * ──────────────────────────────────────────────────────────────────────────────
 * The export converts sRGB → CMYK with a print ICC profile and forces the brand
 * blue to its exact CMYK (scripts/lib/{cmyk-pdf,brand-cmyk}.mjs). This module shows
 * that same result on-screen by applying, per pixel:
 *
 *   · non-brand pixels → a pre-baked 3D LUT (sRGB→CMYK(profile,intent)→sRGB),
 *     generated by scripts/bake-softproof-lut.mjs from the SAME ICC profiles.
 *   · brand-tint pixels → the brand-ink ramp (α·CMYK→sRGB), so the proof shows the
 *     exact printed brand blue, not the ICC's generic conversion — mirroring the
 *     export's brand override (detection identical to brand-cmyk.mjs: a pixel is
 *     "brand" when, taking the tint α = 1 − R/255, its green/blue match KIT_BLUE-
 *     over-white at that α within `tol`).
 *
 * LUTs live under /icc/softproof/. The proof is a screen simulation (depends on the
 * monitor); the physical strike-off remains ground truth.
 */
import type { PrintColor } from '../types'

/** Brand override spec, mirrored from scripts/lib/cmyk-pdf.mjs DEFAULT_BRAND. */
const DEFAULT_BRAND = { rgb: '#0070f9', cmyk: [100, 48, 0, 1] as const, tol: 0.03 }

type BrandSpec = { rgb: string | [number, number, number]; tol?: number } | null

/** Effective brand spec for a doc colour block — explicit `brand` wins (incl. null). */
function resolveBrand(color: PrintColor): BrandSpec {
  const c = color as PrintColor & { brand?: BrandSpec }
  if (Object.prototype.hasOwnProperty.call(c, 'brand')) return c.brand ?? null
  return DEFAULT_BRAND
}

function hexToRgb(hex: string): [number, number, number] {
  const n = parseInt(hex.replace('#', ''), 16)
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff]
}

/** Base name + intent the export would use for this doc. */
export function proofKey(color: PrintColor): { base: string; intent: string } {
  const base = (color.iccProfile.split('/').pop() ?? '').replace(/\.icc$/i, '')
  const intent = color.renderIntent ?? 'relative'
  return { base, intent }
}

/* ── asset loading (cached) ──────────────────────────────────────────────────── */

async function loadImageData(url: string): Promise<ImageData> {
  const img = new Image()
  img.decoding = 'sync'
  img.src = url
  await img.decode()
  const c = document.createElement('canvas')
  c.width = img.naturalWidth
  c.height = img.naturalHeight
  const ctx = c.getContext('2d', { willReadFrequently: true })
  if (!ctx) throw new Error('softProof: no 2d context')
  ctx.drawImage(img, 0, 0)
  return ctx.getImageData(0, 0, c.width, c.height)
}

type Lut = { n: number; data: Uint8ClampedArray }

const lutCache = new Map<string, Promise<Lut>>()
const rampCache = new Map<string, Promise<ImageData>>()

function loadLut(base: string, intent: string): Promise<Lut> {
  const key = `${base}.${intent}`
  let p = lutCache.get(key)
  if (!p) {
    p = loadImageData(`/icc/softproof/${key}.lut.png`).then((img) => {
      // Layout: width = N, height = N·N. Derive N from width; validate the pack.
      const n = img.width
      if (img.height !== n * n) throw new Error(`softProof: bad LUT shape ${img.width}x${img.height}`)
      return { n, data: img.data }
    })
    lutCache.set(key, p)
  }
  return p
}

function loadBrandRamp(base: string): Promise<ImageData> {
  let p = rampCache.get(base)
  if (!p) {
    p = loadImageData(`/icc/softproof/${base}.brand.png`)
    rampCache.set(base, p)
  }
  return p
}

/* ── the per-pixel transform ─────────────────────────────────────────────────── */

/**
 * Soft-proof `src` into a NEW canvas of the same size. Throws (so the caller can
 * fall back to the plain preview) if the LUT for this profile/intent is missing.
 */
export async function applySoftProof(src: HTMLCanvasElement, color: PrintColor): Promise<HTMLCanvasElement> {
  const { base, intent } = proofKey(color)
  const brand = resolveBrand(color)
  const [lut, ramp] = await Promise.all([
    loadLut(base, intent),
    brand ? loadBrandRamp(base) : Promise.resolve(null),
  ])

  const w = src.width
  const h = src.height
  const sctx = src.getContext('2d', { willReadFrequently: true })
  if (!sctx) throw new Error('softProof: no source context')
  const img = sctx.getImageData(0, 0, w, h)
  const px = img.data

  const { n, data: L } = lut
  const scale = (n - 1) / 255

  // Brand detection (only valid for a KIT_BLUE-style hue with red channel 0, exactly
  // like brand-cmyk.mjs). Any other hue → skip the override, LUT-proof every pixel.
  let useBrand = false
  let fG = 0
  let fB = 0
  let tol255 = 0
  let ramps: Uint8ClampedArray | null = null
  if (brand && ramp) {
    const [br, bg, bb] = Array.isArray(brand.rgb) ? brand.rgb : hexToRgb(brand.rgb)
    if (br === 0) {
      useBrand = true
      fG = (255 - bg) / 255
      fB = (255 - bb) / 255
      tol255 = (brand.tol ?? 0.03) * 255
      ramps = ramp.data
    }
  }

  for (let i = 0; i < px.length; i += 4) {
    const R = px[i]
    const G = px[i + 1]
    const B = px[i + 2]

    if (useBrand) {
      const negR = 255 - R
      const gPred = 255 - negR * fG
      const bPred = 255 - negR * fB
      if (Math.abs(G - gPred) <= tol255 && Math.abs(B - bPred) <= tol255) {
        const r4 = negR * 4 // α = negR/255 → ramp column negR (0..255)
        px[i] = ramps![r4]
        px[i + 1] = ramps![r4 + 1]
        px[i + 2] = ramps![r4 + 2]
        continue
      }
    }

    // Trilinear LUT sample. Pixel(rᵢ,gᵢ,bᵢ) offset = ((gᵢ + bᵢ·n)·n + rᵢ)·4.
    const fr = R * scale
    const fg = G * scale
    const fb = B * scale
    const r0 = fr | 0
    const g0 = fg | 0
    const b0 = fb | 0
    const r1 = r0 < n - 1 ? r0 + 1 : r0
    const g1 = g0 < n - 1 ? g0 + 1 : g0
    const b1 = b0 < n - 1 ? b0 + 1 : b0
    const dr = fr - r0
    const dg = fg - g0
    const db = fb - b0

    const w000 = (1 - dr) * (1 - dg) * (1 - db)
    const w100 = dr * (1 - dg) * (1 - db)
    const w010 = (1 - dr) * dg * (1 - db)
    const w110 = dr * dg * (1 - db)
    const w001 = (1 - dr) * (1 - dg) * db
    const w101 = dr * (1 - dg) * db
    const w011 = (1 - dr) * dg * db
    const w111 = dr * dg * db

    const o000 = ((g0 + b0 * n) * n + r0) * 4
    const o100 = ((g0 + b0 * n) * n + r1) * 4
    const o010 = ((g1 + b0 * n) * n + r0) * 4
    const o110 = ((g1 + b0 * n) * n + r1) * 4
    const o001 = ((g0 + b1 * n) * n + r0) * 4
    const o101 = ((g0 + b1 * n) * n + r1) * 4
    const o011 = ((g1 + b1 * n) * n + r0) * 4
    const o111 = ((g1 + b1 * n) * n + r1) * 4

    px[i] =
      L[o000] * w000 + L[o100] * w100 + L[o010] * w010 + L[o110] * w110 +
      L[o001] * w001 + L[o101] * w101 + L[o011] * w011 + L[o111] * w111
    px[i + 1] =
      L[o000 + 1] * w000 + L[o100 + 1] * w100 + L[o010 + 1] * w010 + L[o110 + 1] * w110 +
      L[o001 + 1] * w001 + L[o101 + 1] * w101 + L[o011 + 1] * w011 + L[o111 + 1] * w111
    px[i + 2] =
      L[o000 + 2] * w000 + L[o100 + 2] * w100 + L[o010 + 2] * w010 + L[o110 + 2] * w110 +
      L[o001 + 2] * w001 + L[o101 + 2] * w101 + L[o011 + 2] * w011 + L[o111 + 2] * w111
  }

  const out = document.createElement('canvas')
  out.width = w
  out.height = h
  const octx = out.getContext('2d')
  if (!octx) throw new Error('softProof: no out context')
  octx.putImageData(img, 0, 0)
  return out
}
